name 'chef_server_upgrade'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures a chef server for upgrade'
long_description 'Installs/Configures a chef server for upgrade'
version '0.3.0'
